spring.application.name=management
server.port=${PORT:8057}

# Database Connection
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Disable Open Session In View warning
spring.jpa.open-in-view=false


# Hikari Connection Pool Configuration (Supabase Recommended)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

# Google OAuth2 Configuration
# Spring Security OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

# Used by your custom GoogleAuthService
google.client.id=${GOOGLE_CLIENT_ID}

#Jwt Authentication
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

springdoc.api-docs.enabled=true

spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com
