                    #spring.application.name=management
                    #server.port=8057
                    #
                    #spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
                    #spring.datasource.username=postgres.avcpdmftfuwzanerhtks
                    #spring.datasource.password=UpuBmq2B7EOTE8tr
                    #spring.datasource.driver-class-name=org.postgresql.Driver
                    #
                    #spring.jpa.hibernate.ddl-auto=update
                    #spring.jpa.show-sql=true
                    #spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
                    #spring.jpa.properties.hibernate.format_sql=true


spring.application.name=management
server.port=${PORT:8057}

# Database Connection
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.avcpdmftfuwzanerhtks
spring.datasource.password=UpuBmq2B7EOTE8tr
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Disable Open Session In View warning
spring.jpa.open-in-view=false


# Hikari Connection Pool Configuration (Supabase Recommended)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000