spring.application.name=management
server.port=${PORT:8057}

# Database Connection
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.avcpdmftfuwzanerhtks
spring.datasource.password=UpuBmq2B7EOTE8tr
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Disable Open Session In View warning
spring.jpa.open-in-view=false


# Hikari Connection Pool Configuration (Supabase Recommended)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

# Google OAuth2 Configuration
# Spring Security OAuth2
spring.security.oauth2.client.registration.google.client-id=351561040777-l2ngs3n186qkf3jjgghego19es57qfun.apps.googleusercontent.com

# Used by your custom GoogleAuthService
google.client.id=351561040777-l2ngs3n186qkf3jjgghego19es57qfun.apps.googleusercontent.com

#Jwt Authentication
jwt.secret=myVerySecretKeyForSecurityManagementSystemAuthentication123456789
jwt.expiration=86400000

springdoc.api-docs.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cathrine.hattakatta@gmail.com
spring.mail.password=emvj phad zpdv ocws

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.starttls.required=true