openapi: 3.0.1
info:
  title: Security Guard Management System
  description: Managing the guards data
  version: 1.0.0

paths:
  /security:
    post:
      tags:
        - security
      security:
        - bearerAuth: []
      summary: Add a new guard
      operationId: createGuardDetails
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SecurityDTO'
      responses:
        '201':
          description: Profile created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityDTO'

    get:
      tags:
        - security
      security:
        - bearerAuth: []
      summary: Get all guards details
      operationId: getAllGuards

      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0

        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 5

      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SecurityDTO'



  /auth/register:
    post:
      tags:
        - authentication
      summary: Register a new user
      operationId: registerUser

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestDTO'

      responses:
        '201':
          description: Registration Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponseDTO'

        '400':
          description: Email already exists


  /auth/login:
    post:
      tags:
        - authentication
      summary: Login user
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestDTO'
      responses:
        '200':
          description: Login Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseDTO'
        '401':
          description: Invalid email or password

  /security/search:
    post:
      tags:
        - security
      security:
        - bearerAuth: []
      summary: Search security with advanced filters
      operationId: searchSecurity
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilterDTO'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SecurityDTO'

  /security/{guardId}:
    get:
      tags:
        - security
      security:
        - bearerAuth: []
      summary: Get security by ID
      operationId: getsecurityById
      parameters:
        - name: guardId
          in: path
          required: true
          schema:
            type: integer

      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityDTO'

        '404':
          description: security not found

    put:
      tags:
        - security
      security:
        - bearerAuth: []
      summary: Update a security details
      operationId: updateSecurity

      parameters:
        - name: guardId
          in: path
          required: true
          schema:
            type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SecurityDTO'

      responses:
        '200':
          description: profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityDTO'

    delete:
      tags:
        - security
      security:
        - bearerAuth: []
      summary: Delete profile
      operationId: deleteProfile

      parameters:
        - name: guardId
          in: path
          required: true
          schema:
            type: integer

      responses:
        '200':
          description: Profile deleted successfully
          content:
            application/json:
              schema:
                type: string
                example: "Profile deleted successfully"

  /auth/google:
    post:
      tags:
        - authentication
      summary: Login with Google
      operationId: googleLogin

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoogleLoginRequestDTO'

      responses:
        '200':
          description: Google Login Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseDTO'


  /auth/forgot-password:
    post:
      tags:
        - authentication
      summary: Forgot password request
      operationId: forgotPassword

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequestDTO'

      responses:
        '200':
          description: Reset token generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Reset token generated successfully

                  token:
                    type: string
                    example: 7c8d9f2a-xxxx-xxxx

        '404':
          description: Email not found



  /auth/reset-password:
    post:
      tags:
        - authentication
      summary: Reset password using token
      operationId: resetPassword

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequestDTO'

      responses:
        '200':
          description: Password reset successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Password updated successfully

        '400':
          description: Invalid or expired token

components:
  securitySchemes:

    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    SecurityDTO:
      type: object
      properties:
        guardId:
          type: integer
        name:
          type: string
        address:
          type: string
        age:
          type: integer
        dob:
          type: string
          format: date
        qualification:
          type: string
        shiftType:
          type: string
        experience:
          type: string
        mobile1:
          type: string
        mobile2:
          type: string
        joinedDate:
          type: string
          format: date
        status:
          type: string
          enum:
            - Active
            - InActive
        assignedLocation:
          type: string

    FilterDTO:
      type: object
      description: filter based on data
      properties:
        name:
          type: string
        guardId:
          type: integer
        shiftType:
          type: string
        qualification:
          type: string
        assignedLocation:
          type: string
        status:
          type: string
          enum:
            - Active
            - InActive

    LoginRequestDTO:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: admin@gmail.com

        password:
          type: string
          format: password
          example: admin123

    LoginResponseDTO:
      type: object
      properties:
        userId:
          type: integer
          example: 1

        email:
          type: string
          example: admin@gmail.com

        role:
          type: string
          example: ADMIN

        provider:
          type: string
          example: LOCAL

        name:
          type: string
          example: Cathrine Praba

        picture:
          type: string
          example: https://lh3.googleusercontent.com/a/....

        token:
          type: string

        message:
          type: string
          example: Login Successful


    RegisterRequestDTO:
      type: object
      required:
        - email
        - password
        - role
      properties:
        email:
          type: string
          format: email
          example: anu@gmail.com

        password:
          type: string
          format: password
          example: anu123

        role:
          type: string
          example: USER


    RegisterResponseDTO:
      type: object
      properties:
        userId:
          type: integer
          example: 1

        email:
          type: string
          example: anu@gmail.com

        role:
          type: string
          example: USER

        provider:
          type: string
          example: LOCAL

        message:
          type: string
          example: Registration Successful


    GoogleLoginRequestDTO:
      type: object
      required:
        - idToken
      properties:
        idToken:
          type: string
          description: Google ID Token received from the frontend
          example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...


    ForgotPasswordRequestDTO:
      type: object
      required:
        - email

      properties:
        email:
          type: string
          format: email
          example: admin@gmail.com



    ResetPasswordRequestDTO:
      type: object
      required:
        - token
        - newPassword

      properties:

        token:
          type: string
          example: 7c8d9f2a-xxxx-xxxx

        newPassword:
          type: string
          format: password
          example: newPassword123